version: "3"
services:
  money-balancer:
    image: ghcr.io/dorianim/money-balancer
    restart: unless-stopped
    container_name: money-balancer
    ports:
      - 8000:8000
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/money-balancer/data:/data
    environment:
      - JWT_SECRET=ThisIsAVerySecretString # change this
