version: "3"

services:
  wikijs:
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    image: linuxserver/wikijs:latest
    container_name: wikijs
    restart: unless-stopped
    ports:
      - 8888:3000 # WEB UI
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/wikijs/config:/config
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/wikijs/data:/data
    links:
      - db

  db:
    environment:
      - POSTGRES_PASSWORD=MySecureDatabasePassword
      - POSTGRES_USER=wikijs
      - POSTGRES_DB=wikijs
    container_name: postgresql
    image: postgres:13.4-bullseye
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/wikijs/database:/var/lib/postgresql/data
